/Users/dumitru/projects/coinnext/lib/json_renderer.js:3
blah()
^
ReferenceError: blah is not defined
  at Object.<anonymous> (/Users/dumitru/projects/coinnext/lib/json_renderer.js:3:1)
  at Object.<anonymous> (/Users/dumitru/projects/coinnext/lib/json_renderer.js:327:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/dumitru/projects/coinnext/lib/sockets.js:30:18)
  at Object.<anonymous> (/Users/dumitru/projects/coinnext/lib/sockets.js:110:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/dumitru/projects/coinnext/app.js:85:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:901:3